local turndown_freq_words =
{ 	["冇"] = { "mc", },
	["调孙"] = { "dnsy", },
	["车是"] = { "ieui", },
	["郑损"] = { "vgsy", },
	["石菖蒲"] = { "uiihp", },
	["捉对"] = { "vodv", },
	["爬船"] = { "pair", },
	["调笋"] = { "dnsy", },
	["官婢"] = { "grbi", },
	["搭脉"] = { "damd", },
	["不干胶"] = { "bugjj", },
	["大特"] = { "date", },
	["结社"] = { "jpue", },
	["微生建"] = { "wwugjm", },
	["爬松"] = { "pass", },
	["则可"] = { "zeke", },
	["佛莱尔"] = { "folder", },
	["托达亚"] = { "today", },
	["乾"] = { "gj[u", },
	["达特"] = { "date", },
}
return turndown_freq_words