local commands = {
	["Windows"] = {
		["jjcm"] = { "CMD", "cmd.exe" },
		["jjdn"] = { "Explorer", "::{20D04FE0-3AEA-1069-A2D8-08002B30309D}" },
		["jjec"] = { "Excel", "excel.exe" },
		["jjwd"] = { "Word", "word.exe" },
		["jjht"] = { "画图", "mspaint.exe" },
		["jjjs"] = { "计算器", "calc.exe" },
	},
	["Darwin"] = {
		["jjjt"] = { "截图", "com.apple.screenshot.launcher" },
		["jjss"] = { "截图", "com.apple.screenshot.launcher" },
		["jjam"] = { "任务监视器", "com.apple.ActivityMonitor" },
		["jjtm"] = { "任务监视器", "com.apple.ActivityMonitor" },
		["jjsp"] = { "系统设置", "com.apple.systempreferences" },
		["jjfl"] = { "ForkLift", "com.binarynights.ForkLift-3" },
		["jjfd"] = { "Finder", "com.apple.finder" },
		["jjsf"] = { "Safari 浏览器", "com.apple.Safari" },
		["jjgc"] = { "Chrome 浏览器", "com.google.Chrome" },
		["jjch"] = { "Chrome 浏览器", "com.google.Chrome" },
		["jjff"] = { "火狐浏览器", "org.mozilla.firefox" },
		["jjfy"] = { "Easydict", "com.izual.Easydict" },
		["jjed"] = {
			{ "Edge 浏览器", "com.microsoft.edgemac" },
			{ "Easy 词典", "com.izual.Easydict" },
			{ "Eudic", "com.eusoft.eudic" },
		},
		["jjol"] = { "Outlook 邮箱", "com.microsoft.Outlook" },
		["jjwm"] = { "网易云音乐", "com.netease.163music" },
		["jjqw"] = { "企业微信", "com.tencent.WeWorkMac" },
		["jjww"] = { "企业微信", "com.tencent.WeWorkMac" },
		["jjwx"] = { "微信", "com.tencent.xinWeChat" },
		["jjwc"] = { "微信", "com.tencent.xinWeChat" },
		["jjqq"] = { "QQ", "com.tencent.qq" },
		["jjnv"] = { "Neovide", "com.neovide.neovide" },
		["jjvc"] = { "VSCode", "com.microsoft.VSCode" },
		["jjob"] = { "Obsidian", "md.obsidian" },
		["jjat"] = { "alacritty 终端", "org.alacritty" },
		["jjit"] = { "iTerm2 终端", "com.googlecode.iterm2" },
		["jjdl"] = { "FDM 下载", "org.freedownloadmanager.fdm6" },
	},
	["Favor"] = {
		["mb邮箱"] = {
			"boomker@gmail.com",
			"zhu@yamutech.com",
			"ichigo@outlook.com",
		},
		["bm书签"] = {
			"https://youtube.com",
			"https://bilibili.com",
			"https://github.com",
			"https://mail.google.com",
		},
		["cn卡号"] = {
			["电信个人"] = "10000000000",
			["移动工作"] = "10000000000",
			["招商工资"] = "6000000000099999",
			["身份证号"] = "400000000009999999",
		},
		["fl目录位置"] = {
			["打开下载文件夹"] = "~/Downloads",
			["打开文档文件夹"] = "~/Documents",
		},
	},
	["iOS"] = {},
}

return commands
