local reduce_freq_words =
{ 	["Photoshop"] = { "ps", },
	["书裙"] = { "uuqy", },
	["D组"] = { "dzu", },
	["大V"] = { "dav", },
	["颜射"] = { "yjue", },
	["加Q"] = { "jxq", },
	["肏屄"] = { "ccbi", },
	["萨法"] = { "safa", },
	["Y轴"] = { "yvz", },
	["X轴"] = { "xvz", },
	["圈X"] = { "qrx", },
	["X11"] = { "xwi", },
	["B面"] = { "bmm", },
	["恩特"] = { "ente", },
	["佛莱尔"] = { "folder", },
	["x64"] = { "xlf", },
	["官婢"] = { "grbi", },
	["爬船"] = { "pair", },
	["vivid"] = { "vivid", },
}
return reduce_freq_words